# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for
import easyrpc.conformance.v1.conformance_pb2 as m
import asyncio

class ConformanceServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def health(self, req: m.HealthRequest, kind: str = "proto") -> m.HealthResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Health", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.HealthResponse, kind)

    async def echo(self, req: m.EchoRequest, kind: str = "proto") -> m.EchoResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Echo", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.EchoResponse, kind)

    async def count(self, req: m.CountRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/Count", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.CountResponse, kind))

    async def fail(self, req: m.FailRequest, kind: str = "proto") -> m.FailResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Fail", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.FailResponse, kind)

    async def streamFail(self, req: m.StreamFailRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/StreamFail", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.StreamFailResponse, kind))

    async def echoMeta(self, req: m.EchoMetaRequest, kind: str = "proto") -> m.EchoMetaResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/EchoMeta", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.EchoMetaResponse, kind)

    async def big(self, req: m.BigRequest, kind: str = "proto") -> m.BigResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Big", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.BigResponse, kind)

    async def failDetails(self, req: m.FailDetailsRequest, kind: str = "proto") -> m.FailDetailsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/FailDetails", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.FailDetailsResponse, kind)

    async def streamFailDetails(self, req: m.StreamFailDetailsRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/StreamFailDetails", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.StreamFailDetailsResponse, kind))

    async def echoTrailer(self, req: m.EchoTrailerRequest, kind: str = "proto") -> m.EchoTrailerResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/EchoTrailer", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.EchoTrailerResponse, kind)

    async def countTrailer(self, req: m.CountTrailerRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/CountTrailer", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.CountTrailerResponse, kind))

    async def echoBytes(self, req: m.EchoBytesRequest, kind: str = "proto") -> m.EchoBytesResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/EchoBytes", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.EchoBytesResponse, kind)

    async def sleep(self, req: m.SleepRequest, kind: str = "proto") -> m.SleepResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Sleep", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.SleepResponse, kind)

    async def empty(self, req: m.EmptyRequest, kind: str = "proto") -> m.EmptyResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Empty", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.EmptyResponse, kind)

    async def bigStream(self, req: m.BigStreamRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/BigStream", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.BigStreamResponse, kind))
