# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream
import easyrpc.conformance.v1.conformance_pb2 as m
import asyncio

class ConformanceServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def health(self, req: m.HealthRequest) -> m.HealthResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Health", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.HealthResponse.FromString(res.body)

    async def echo(self, req: m.EchoRequest) -> m.EchoResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Echo", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.EchoResponse.FromString(res.body)

    async def count(self, req: m.CountRequest):
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/Count", body=frame(req.SerializeToString())))
        return TypedStream(st, lambda b: m.CountResponse.FromString(b))

    async def fail(self, req: m.FailRequest) -> m.FailResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Fail", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.FailResponse.FromString(res.body)

    async def streamFail(self, req: m.StreamFailRequest):
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/StreamFail", body=frame(req.SerializeToString())))
        return TypedStream(st, lambda b: m.StreamFailResponse.FromString(b))

    async def echoMeta(self, req: m.EchoMetaRequest) -> m.EchoMetaResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/EchoMeta", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.EchoMetaResponse.FromString(res.body)

    async def big(self, req: m.BigRequest) -> m.BigResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/Big", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.BigResponse.FromString(res.body)

    async def failDetails(self, req: m.FailDetailsRequest) -> m.FailDetailsResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/FailDetails", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.FailDetailsResponse.FromString(res.body)

    async def streamFailDetails(self, req: m.StreamFailDetailsRequest):
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/StreamFailDetails", body=frame(req.SerializeToString())))
        return TypedStream(st, lambda b: m.StreamFailDetailsResponse.FromString(b))

    async def echoTrailer(self, req: m.EchoTrailerRequest) -> m.EchoTrailerResponse:
        res = await self._t.send(Request(url="/easyrpc.conformance.v1.ConformanceService/EchoTrailer", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.EchoTrailerResponse.FromString(res.body)

    async def countTrailer(self, req: m.CountTrailerRequest):
        st = await self._t.open_stream(Request(url="/easyrpc.conformance.v1.ConformanceService/CountTrailer", body=frame(req.SerializeToString())))
        return TypedStream(st, lambda b: m.CountTrailerResponse.FromString(b))
