# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: easyrpc/conformance/v1/conformance.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'easyrpc/conformance/v1/conformance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(easyrpc/conformance/v1/conformance.proto\x12\x16\x65\x61syrpc.conformance.v1\x1a\x1cgoogle/api/annotations.proto\"\x1c\n\x0b\x45\x63hoRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0c\x45\x63hoResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\"\x1d\n\x0c\x43ountRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x1e\n\rCountResponse\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1e\n\x0b\x46\x61ilRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x0c\x46\x61ilResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x0f\n\rHealthRequest\"*\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t2\xbf\x03\n\x12\x43onformanceService\x12k\n\x06Health\x12%.easyrpc.conformance.v1.HealthRequest\x1a&.easyrpc.conformance.v1.HealthResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/health\x12\x66\n\x04\x45\x63ho\x12#.easyrpc.conformance.v1.EchoRequest\x1a$.easyrpc.conformance.v1.EchoResponse\"\x13\x82\xd3\xe4\x93\x02\r\"\x08/v1/echo:\x01*\x12l\n\x05\x43ount\x12$.easyrpc.conformance.v1.CountRequest\x1a%.easyrpc.conformance.v1.CountResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/count:\x01*0\x01\x12\x66\n\x04\x46\x61il\x12#.easyrpc.conformance.v1.FailRequest\x1a$.easyrpc.conformance.v1.FailResponse\"\x13\x82\xd3\xe4\x93\x02\r\"\x08/v1/fail:\x01*B@Z>github.com/easy-utils/easy-rpc-go/conformance/v1;conformancev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'easyrpc.conformance.v1.conformance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/easy-utils/easy-rpc-go/conformance/v1;conformancev1'
  _globals['_CONFORMANCESERVICE'].methods_by_name['Health']._loaded_options = None
  _globals['_CONFORMANCESERVICE'].methods_by_name['Health']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/health'
  _globals['_CONFORMANCESERVICE'].methods_by_name['Echo']._loaded_options = None
  _globals['_CONFORMANCESERVICE'].methods_by_name['Echo']._serialized_options = b'\202\323\344\223\002\r\"\010/v1/echo:\001*'
  _globals['_CONFORMANCESERVICE'].methods_by_name['Count']._loaded_options = None
  _globals['_CONFORMANCESERVICE'].methods_by_name['Count']._serialized_options = b'\202\323\344\223\002\016\"\t/v1/count:\001*'
  _globals['_CONFORMANCESERVICE'].methods_by_name['Fail']._loaded_options = None
  _globals['_CONFORMANCESERVICE'].methods_by_name['Fail']._serialized_options = b'\202\323\344\223\002\r\"\010/v1/fail:\001*'
  _globals['_ECHOREQUEST']._serialized_start=98
  _globals['_ECHOREQUEST']._serialized_end=126
  _globals['_ECHORESPONSE']._serialized_start=128
  _globals['_ECHORESPONSE']._serialized_end=158
  _globals['_COUNTREQUEST']._serialized_start=160
  _globals['_COUNTREQUEST']._serialized_end=189
  _globals['_COUNTRESPONSE']._serialized_start=191
  _globals['_COUNTRESPONSE']._serialized_end=221
  _globals['_FAILREQUEST']._serialized_start=223
  _globals['_FAILREQUEST']._serialized_end=253
  _globals['_FAILRESPONSE']._serialized_start=255
  _globals['_FAILRESPONSE']._serialized_end=281
  _globals['_HEALTHREQUEST']._serialized_start=283
  _globals['_HEALTHREQUEST']._serialized_end=298
  _globals['_HEALTHRESPONSE']._serialized_start=300
  _globals['_HEALTHRESPONSE']._serialized_end=342
  _globals['_CONFORMANCESERVICE']._serialized_start=345
  _globals['_CONFORMANCESERVICE']._serialized_end=792
# @@protoc_insertion_point(module_scope)
