#!/usr/bin/env python3
# protoc-gen-easyrpc-python: emit <file>_easyrpc_pb2.py strong-typed client.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            out.append((svc.name, m.name or '', f'/{pkg}.{svc.name}/{m.name}', m.server_streaming, m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        L=['# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.',
           'from easyrpc import Transport, Request',
           'from easyrpc.conformance.v1 import conformance_pb2 as m',
           'import asyncio','',
           'class ConformanceServiceClient:',
           '    def __init__(self, transport: Transport): self._t = transport','']
        for (svc,name,path,ss,it,ot) in ms:
            if ss:
                L.append('    async def %s(self, req: m.%s) -> "AsyncIterator[m.%s]":' % (camel(name), it, ot))
                L.append('        st = await self._t.open_stream(Request(url="%s", body=req.SerializeToString()))' % path)
                L.append('        async for chunk in st: yield m.%s.FromString(chunk)' % ot)
                L.append('')
            else:
                L.append('    async def %s(self, req: m.%s) -> m.%s:' % (camel(name), it, ot))
                L.append('        res = await self._t.send(Request(url="%s", body=req.SerializeToString()))' % path)
                L.append('        if res.error: raise res.error')
                L.append('        return m.%s.FromString(res.body)' % ot)
                L.append('')
        content='\n'.join(L)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc_pb2.py', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

def camel(s): return s[:1].lower()+s[1:]
if __name__=='__main__': main()
