#!/usr/bin/env python3
# protoc-gen-easyrpc-python: read CodeGeneratorRequest, emit <file>_easyrpc_pb2.py
# containing a method table + strong-typed client harness. Uses google.protobuf.
import sys, os
from google.protobuf.compiler import plugin_pb2 as plugin
from google.protobuf import descriptor_pb2 as desc
from google.protobuf.descriptor_pb2 import MethodOptions

def varint(b,i):
    v=0;s=0
    while True:
        x=b[i];i+=1;v|=(x&0x7f)<<s;s+=7
        if not x&0x80: break
    return v,i

def http_rule(m):
    # uninterpretedOption with aggregate value OR unknown field 72295728
    opts=m.options
    if not opts: return None
    has_u=opts.HasField('uninterpreted_option') if False else False
    # try unknown via serialized: too complex offline; rely on fallback path.
    return None

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            name=m.name or ''
            path=f'/{pkg}.{svc.name}/{name}'
            out.append((pkg, svc.name, name, path, m.client_streaming, m.server_streaming))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        lines=['# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.','METHOD_SPECS = [',
               '']
        for (pkg,svc,name,path,cs,ss) in ms:
            lines.append(f'  {{"service":"{pkg}.{svc}","name":"{name}","path":"{path}","http_method":"POST","client_stream":{cs},"server_stream":{ss}}},')
        lines.append(']')
        lines.append('')
        content='\n'.join(lines)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc_pb2.py', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

if __name__=='__main__': main()
