#!/usr/bin/env python3
# protoc-gen-easyrpc-python: emit <file>_easyrpc_pb2.py strong-typed client.
#
# Package-aware: the message import path and client class name are derived from
# the proto, so any package (e.g. agent.v1) is generated instead of hard-coding
# conformance. EASYRPC_PY_LIB controls the generated cross-package library root
# (default 'easyrpc').
import os
import sys
from google.protobuf.compiler import plugin_pb2 as plugin


def resolve(f):
    out = []
    pkg = f.package or ''
    for svc in f.service:
        for m in svc.method:
            path = f'/{pkg}.{svc.name}/{m.name}'
            out.append((svc.name, m.name or '', path, m.server_streaming,
                        m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out



def readvar(b, i):
    v = 0
    s = 0
    while True:
        x = b[i] if i < len(b) else 0
        i += 1
        v |= (x & 0x7f) << s
        s += 7
        if not x & 0x80:
            break
    return v, i


def parse_rule(d):
    i = 0
    while i < len(d):
        tag, i = readvar(d, i)
        field = tag >> 3
        wt = tag & 7
        if wt == 2:
            ln, i = readvar(d, i)
            val = d[i:i + ln].decode()
            i += ln
            if field in (2, 4, 3, 6):
                return val
        elif wt == 0:
            _, i = readvar(d, i)
        elif wt == 5:
            i += 4
        elif wt == 1:
            i += 8
    return None


def main():
    data = sys.stdin.buffer.read()
    req = plugin.CodeGeneratorRequest.FromString(data)
    lib = os.environ.get('EASYRPC_PY_LIB', 'easyrpc')
    # Message module: <lib>.<pkg dirs>/<base>_pb2, with '.' -> '_'.
    files = []
    for f in req.proto_file:
        if f.name not in req.file_to_generate:
            continue
        ms = resolve(f)
        if not ms:
            continue
        base = f.name[:-6]                       # strip .proto (incl dirs)
        pkg_dir = os.path.dirname(f.name).replace('\\', '/')
        parts = pkg_dir.split('/') if pkg_dir else []
        if parts and parts[0] == lib:
            parts = parts[1:]
        pkg_dir = '/'.join(parts)
        # protobuf module segments use underscore for dots in package, but path keeps '/' so we keep dirs as-is and only sanitize final module.
        pkg_dir = pkg_dir.replace('.', '_')
        mod_base = os.path.basename(base)
        # Avoid duplicating the library segment when the proto path already starts with it.
        if pkg_dir.split('.')[0] == lib:
            mod_path = f"{pkg_dir}/{mod_base}_pb2"
        else:
            mod_path = f"{lib}.{pkg_dir}/{mod_base}_pb2" if pkg_dir else f"{lib}.{mod_base}_pb2"
        mod_path = mod_path.replace('/', '.')
        # One output file per SERVICE (multi-service protos must not collapse
        # into a single class).
        service_names = sorted({svc for (svc, _n, _p, _s, _i, _o) in ms})
        multi = len(service_names) > 1
        for svc_name in service_names:
            service_methods = [x for x in ms if x[0] == svc_name]
            client = svc_name + 'Client'
            L = ['# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.',
                 'from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for',
                 f'import {mod_path} as m',
                 'import asyncio', '',
                 f'class {client}:',
                 '    def __init__(self, transport: Transport):',
                 '        self._t = transport',
                 '        self.last_trailers = {}', '']
            for (svc, name, path, ss, it, ot) in service_methods:
                if ss:
                    L.append('    async def %s(self, req: m.%s, kind: str = "proto"):' % (camel(name), it))
                    L.append('        ct = content_type_for(True, kind)')
                    L.append('        st = await self._t.open_stream(Request(url="%s", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))' % path)
                    L.append('        return TypedStream(st, lambda b: decode_msg(b, m.%s, kind))' % ot)
                    L.append('')
                else:
                    L.append('    async def %s(self, req: m.%s, kind: str = "proto") -> m.%s:' % (camel(name), it, ot))
                    L.append('        ct = content_type_for(False, kind)')
                    L.append('        res = await self._t.send(Request(url="%s", headers={"content-type": [ct]}, body=encode_msg(req, kind)))' % path)
                    L.append('        if res.error: raise res.error')
                    L.append('        self.last_trailers = res.trailers')
                    L.append('        return decode_msg(res.body, m.%s, kind)' % ot)
                    L.append('')
            suffix = ('_' + svc_name) if multi else ''
            content = '\n'.join(L)
            files.append(plugin.CodeGeneratorResponse.File(name=base + suffix + '_easyrpc_pb2.py', content=content))
    resp = plugin.CodeGeneratorResponse(file=files)
    resp.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    sys.stdout.buffer.write(resp.SerializeToString())


def camel(s):
    return s[:1].lower() + s[1:]


if __name__ == '__main__':
    main()
