# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream
import easyrpc.connectrpc.conformance.v1.service_pb2 as m
import asyncio

class ConformanceServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def unary(self, req: m.UnaryRequest) -> m.UnaryResponse:
        res = await self._t.send(Request(url="/connectrpc.conformance.v1.ConformanceService/Unary", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.UnaryResponse.FromString(res.body)

    async def serverStream(self, req: m.ServerStreamRequest):
        st = await self._t.open_stream(Request(url="/connectrpc.conformance.v1.ConformanceService/ServerStream", body=frame(req.SerializeToString())))
        return TypedStream(st, lambda b: m.ServerStreamResponse.FromString(b))

    async def clientStream(self, req: m.ClientStreamRequest) -> m.ClientStreamResponse:
        res = await self._t.send(Request(url="/connectrpc.conformance.v1.ConformanceService/ClientStream", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.ClientStreamResponse.FromString(res.body)

    async def bidiStream(self, req: m.BidiStreamRequest):
        st = await self._t.open_stream(Request(url="/connectrpc.conformance.v1.ConformanceService/BidiStream", body=frame(req.SerializeToString())))
        return TypedStream(st, lambda b: m.BidiStreamResponse.FromString(b))

    async def unimplemented(self, req: m.UnimplementedRequest) -> m.UnimplementedResponse:
        res = await self._t.send(Request(url="/connectrpc.conformance.v1.ConformanceService/Unimplemented", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.UnimplementedResponse.FromString(res.body)

    async def idempotentUnary(self, req: m.IdempotentUnaryRequest) -> m.IdempotentUnaryResponse:
        res = await self._t.send(Request(url="/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", body=req.SerializeToString()))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return m.IdempotentUnaryResponse.FromString(res.body)
