# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: connectrpc/conformance/v1/server_compat.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'connectrpc/conformance/v1/server_compat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from connectrpc.conformance.v1 import config_pb2 as connectrpc_dot_conformance_dot_v1_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-connectrpc/conformance/v1/server_compat.proto\x12\x19\x63onnectrpc.conformance.v1\x1a&connectrpc/conformance/v1/config.proto\"\x8e\x02\n\x13ServerCompatRequest\x12\x35\n\x08protocol\x18\x01 \x01(\x0e\x32#.connectrpc.conformance.v1.Protocol\x12<\n\x0chttp_version\x18\x02 \x01(\x0e\x32&.connectrpc.conformance.v1.HTTPVersion\x12\x0f\n\x07use_tls\x18\x04 \x01(\x08\x12\x17\n\x0f\x63lient_tls_cert\x18\x05 \x01(\x0c\x12\x1d\n\x15message_receive_limit\x18\x06 \x01(\r\x12\x39\n\x0cserver_creds\x18\x07 \x01(\x0b\x32#.connectrpc.conformance.v1.TLSCreds\"D\n\x14ServerCompatResponse\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x10\n\x08pem_cert\x18\x03 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connectrpc.conformance.v1.server_compat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERCOMPATREQUEST']._serialized_start=117
  _globals['_SERVERCOMPATREQUEST']._serialized_end=387
  _globals['_SERVERCOMPATRESPONSE']._serialized_start=389
  _globals['_SERVERCOMPATRESPONSE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
